export enum Routes {
  AUTH = 'auth',
  USERS = 'users',
  CONVERSATIONS = 'conversations',
  MESSAGES = 'messages',
  PROFILE_SERVICE = 'profiles',
  POSTS = 'posts',
  COMMENTS = 'comments',
}

export enum Services {
  AUTH = 'AUTH_SERVICES',
  USERS = 'USERS_SERVICES',
  CONVERSATIONS = 'CONVERSATIONS',
  MESSAGES = 'MESSAGES_SERVICE',
  GATEWAY_SESSION = 'GATEWAY_SESSION',
  PROFILE_SERVICE = 'PROFILE_SERVICE',
  POST_SERVICE = 'POST_SERVICE',
  STRIPE_SERVICE = 'STRIPE_SERVICE',
}

export const jwtConstants = {
  secret:
    'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
};
